name: New theme
description: Submit a new theme for review!
labels: "New theme"
title: "[New Theme]: "
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for contributing!
        Please write name of the theme in the title, then fill in the details.
  - type: textarea
    id: themezip
    attributes:
      label: Theme ZIP
      placeholder: |
        Attach the zip file of the theme by drag and dropping or selecting upload.
    validations:
      required: true
